### ISSUE TITLE
packetfabric_cloud_services_gcp_req_hosted_conn: panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#56]
Run into this error when trying to use `packetfabric_cloud_services_gcp_req_hosted_conn`:

**Terraform config:**
```
terraform {
  required_providers {
    packetfabric = {
      # source  = "PacketFabric/packetfabric"
      # version = "0.2.0"
      source  = "terraform.local/PacketFabric/packetfabric"
      version = "~> 0.0.0"
    }
  }
}

provider "packetfabric" {
  host  = var.pf_api_server
  token = var.pf_api_key
}

# Create random name to use to name objects
resource "random_pet" "name" {}

resource "packetfabric_interface" "interface_1" {
  provider          = packetfabric
  account_uuid      = var.pf_account_uuid
  autoneg           = var.pf_interface_autoneg
  description       = "${var.tag_name}-${random_pet.name.id}"
  media             = var.pf_interface_media
  nni               = var.pf_interface_nni
  pop               = var.pf_interface_pop1
  speed             = var.pf_interface_speed
  subscription_term = var.pf_interface_subterm
  zone              = var.pf_interface_avzone1
}

resource "packetfabric_cloud_services_gcp_req_hosted_conn" "cs_conn1" {
  provider = packetfabric
  description = "${var.tag_name}-${random_pet.name.id}"
  account_uuid = var.pf_account_uuid
  port = packetfabric_interface.interface_1.id
  speed = var.pf_cs_speed
  googe_pairing_key = var.service_key
  google_vlan_attachment_name = var.vlan_attachement_name
  pop = var.pf_cs_pop1
  vlan = var.pf_cs_vlan1
}
```

**Output**:
```
packetfabric_cloud_services_gcp_req_hosted_conn.cs_conn1: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with packetfabric_cloud_services_gcp_req_hosted_conn.cs_conn1,
│   on main.tf line 68, in resource "packetfabric_cloud_services_gcp_req_hosted_conn" "cs_conn1":
│   68: resource "packetfabric_cloud_services_gcp_req_hosted_conn" "cs_conn1" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange
│ call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-packetfabric plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 60 [running]:
github.com/PacketFabric/terraform-provider-packetfabric/internal/provider.extractGoogleReqConn(0x11f3620?)
	/working/terraform-provider-packetfabric/internal/provider/resource_google_request_hosted_conn.go:110 +0x3c5
github.com/PacketFabric/terraform-provider-packetfabric/internal/provider.resourceGoogleReqHostConnCreate({0xd5e948?, 0xc0003c2900?}, 0xb600e0?, {0xc33b40?, 0xc0002c3080})
	/working/terraform-provider-packetfabric/internal/provider/resource_google_request_hosted_conn.go:83 +0x8d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0000b3dc0, {0xd5e980, 0xc00039dfb0}, 0xd?, {0xc33b40, 0xc0002c3080})
	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.15.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000b3dc0, {0xd5e980, 0xc00039dfb0}, 0xc000429380, 0xc000127900, {0xc33b40, 0xc0002c3080})
	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.15.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0001ca3d8, {0xd5e8d8?, 0xc000283a00?}, 0xc0003cc7d0)
	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.15.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001dcb40, {0xd5e980?, 0xc00039d9b0?}, 0xc0004fb2d0)
	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc0a500?, 0xc0001dcb40}, {0xd5e980, 0xc00039d9b0}, 0xc0003c2420, 0x0)
	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002308c0, {0xd616b0, 0xc000003a00}, 0xc000425440, 0xc000353620, 0x11e5b00, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0002308c0, {0xd616b0, 0xc000003a00}, 0xc000425440, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/root/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/root/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a

Error: The terraform-provider-packetfabric plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Comment by pontovinte** [comment]
This issue got solved together with issue #65.
