### ISSUE TITLE
interface conversion: interface {} is nil, not int on src_svlan

### ISSUE THREAD

**Issue by medzin** [PacketFabric/terraform-provider-packetfabric#62]
For the following resource:

```hcl
resource "packetfabric_cloud_services_aws_hosted_connection" "medzin" {
  account_uuid   = local.default_billing_account_uuid
  aws_account_id = "1234567890"
  description    = "test-aws-medzin-uat"
  pop            = "LAX1"
  port           = "test"
  speed          = "50Mbps"
  vlan           = 4
  src_svlan      = 5
}
```

I get the following error:

```
panic: interface conversion: interface {} is nil, not int

goroutine 71 [running]:
github.com/PacketFabric/terraform-provider-packetfabric/internal/provider.extractAwsHostedMktConn(0xc0000bb860?)
        /home/medzin/repos/terraform-provider-packetfabric/internal/provider/resource_aws_hosted_mkt_conn.go:117 +0x39c
github.com/PacketFabric/terraform-provider-packetfabric/internal/provider.resourceAwsHostedMktConnCreate({0xd5d628?, 0xc0000bb860?}, 0xb5f0e0?, {0xc32b40?, 0xc0000bafc0})
        /home/medzin/repos/terraform-provider-packetfabric/internal/provider/resource_aws_hosted_mkt_conn.go:86 +0x8d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0003d8a80, {0xd5d660, 0xc000303050}, 0xd?, {0xc32b40, 0xc0000bafc0})
        /home/medzin/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.15.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003d8a80, {0xd5d660, 0xc000303050}, 0xc0004f71e0, 0xc00053db80, {0xc32b40, 0xc0000bafc0})
        /home/medzin/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.15.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000311188, {0xd5d5b8?, 0xc00011d040?}, 0xc000716aa0)
        /home/medzin/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.15.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00036c460, {0xd5d660?, 0xc0003027e0?}, 0xc00022e2a0)
        /home/medzin/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc09500?, 0xc00036c460}, {0xd5d660, 0xc0003027e0}, 0xc0000bb0e0, 0x0)
        /home/medzin/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000328700, {0xd60390, 0xc0004216c0}, 0xc000585b00, 0xc0003f5b60, 0x11e6b40, 0x0)
        /home/medzin/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc000328700, {0xd60390, 0xc0004216c0}, 0xc000585b00, 0x0)
        /home/medzin/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/medzin/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/medzin/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a

Error: The terraform-provider-packetfabric plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue
```

**Comment by pontovinte** [comment]
Fixed misspelling for `src_svlan` on current open PR.
