### ISSUE TITLE
packetfabric_cloud_router: panic: interface conversion: interface {} is []interface {}, not *schema.Set

### ISSUE THREAD

**Issue by rjouhann** [PacketFabric/terraform-provider-packetfabric#69]
I was re-trying the existing [cloud_router_aws use case example](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/feature/google-service/examples/use-cases/cloud_router_aws) with the latest code on `feature/google-service` branch and the provider crashed at the Cloud Router creation. see below

```
packetfabric_cloud_router.cr: Creating...

╷
│ Error: Plugin did not respond
│ 
│   with packetfabric_cloud_router.cr,
│   on main.tf line 365, in resource "packetfabric_cloud_router" "cr":
│  365: resource "packetfabric_cloud_router" "cr" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin
│ logs may contain more details.
╵

Stack trace from the terraform-provider-packetfabric plugin:

panic: interface conversion: interface {} is []interface {}, not *schema.Set

goroutine 31 [running]:
github.com/PacketFabric/terraform-provider-packetfabric/internal/provider.extractRegions(0x10?)
	/working/terraform-provider-packetfabric/internal/provider/resource_cloud_router.go:186 +0x2f6
github.com/PacketFabric/terraform-provider-packetfabric/internal/provider.extractCloudRouter(0xd602c0?)
	/working/terraform-provider-packetfabric/internal/provider/resource_cloud_router.go:179 +0x1d0
github.com/PacketFabric/terraform-provider-packetfabric/internal/provider.resourceCloudRouterCreate({0xd60288?, 0xc0000cb320?}, 0xb615e0?, {0xc35880?, 0xc0003b0480})
	/working/terraform-provider-packetfabric/internal/provider/resource_cloud_router.go:85 +0x8a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0001229a0, {0xd602c0, 0xc0004daae0}, 0xd?, {0xc35880, 0xc0003b0480})
	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.15.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001229a0, {0xd602c0, 0xc0004daae0}, 0xc000099380, 0xc000091c80, {0xc35880, 0xc0003b0480})
	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.15.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002423f0, {0xd60218?, 0xc00007ee40?}, 0xc0004ac9b0)
	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.15.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000254d20, {0xd602c0?, 0xc0004da300?}, 0xc000489b20)
	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc0bb20?, 0xc000254d20}, {0xd602c0, 0xc0004da300}, 0xc0000cac00, 0x0)
	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a88c0, {0xd62ff0, 0xc000003d40}, 0xc000405320, 0xc00034b6b0, 0x11e7b20, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0002a88c0, {0xd62ff0, 0xc000003d40}, 0xc000405320, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/root/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/root/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a

Error: The terraform-provider-packetfabric plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by rjouhann** [comment]
Verified fix in [feature/google-service](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/feature/google-service) branch
